{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "CONTRIBUTOR",
   "body" : "**Edit: root issue fixed in #25990, closing this.**\r\n\r\n---\r\n\r\nAs described in #25940, `test/functional/wallet_groups.py` suddenly started failing intermittently. Even though there are no explanations yet, this seems to be significantly exacerbated or introduced by #25865. This PR patches that by reverting the [change](https://github.com/bitcoin/bitcoin/pull/25865/files#diff-2749503331922c402bb3207619effd4f17a45286f57267b1bc3b48ef0a0ffb14) (only to `wallet_groups.py`) without addressing the root issue, as to quickly unbreak CI which is failing quite often now.\r\n\r\n**Should be followed-up with a proper fix since it's not immediately obvious that #25865 should have led to wallet_groups.py failing intermittently.**\r\n\r\nI did empirical testing to verify that the test started failing because of #25865 by running wallet_groups.py until it failed, first on commit b21e522ce (the HEAD of #25865) and then on a75b7796b (the HEAD right before #25865). On b21e522ce (i.e. with #25865), it took about ~9.2 runs (n=6) on average before the test failed. On the previous commit a75b7796b (i.e. without #25865), I didn't get a single failure after running the test 100 times.\r\n\r\nWith this PR, I didn't get a single failure after 240 runs.",
   "closed_at" : "2022-09-03T00:34:14Z",
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/69010457?v=4",
      "events_url" : "https://api.github.com/users/stickies-v/events{/privacy}",
      "followers_url" : "https://api.github.com/users/stickies-v/followers",
      "following_url" : "https://api.github.com/users/stickies-v/following{/other_user}",
      "gists_url" : "https://api.github.com/users/stickies-v/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/stickies-v",
      "id" : 69010457,
      "login" : "stickies-v",
      "node_id" : "MDQ6VXNlcjY5MDEwNDU3",
      "organizations_url" : "https://api.github.com/users/stickies-v/orgs",
      "received_events_url" : "https://api.github.com/users/stickies-v/received_events",
      "repos_url" : "https://api.github.com/users/stickies-v/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/stickies-v/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/stickies-v/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/stickies-v"
   },
   "comments" : 1,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25988/comments",
   "created_at" : "2022-09-02T17:45:32Z",
   "draft" : false,
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25988/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/25988",
   "id" : 1360463684,
   "labels" : [
      {
         "color" : "d4c5f9",
         "default" : false,
         "description" : null,
         "id" : 62963516,
         "name" : "Tests",
         "node_id" : "MDU6TGFiZWw2Mjk2MzUxNg==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25988/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "PR_kwDOABII584-S8Pd",
   "number" : 25988,
   "performed_via_github_app" : null,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/25988.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/25988",
      "merged_at" : null,
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/25988.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/25988"
   },
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25988/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "state_reason" : null,
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25988/timeline",
   "title" : "test: revert #25865 for wallet_groups.py (quick fix)",
   "updated_at" : "2022-09-03T00:34:14Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/25988",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/69010457?v=4",
      "events_url" : "https://api.github.com/users/stickies-v/events{/privacy}",
      "followers_url" : "https://api.github.com/users/stickies-v/followers",
      "following_url" : "https://api.github.com/users/stickies-v/following{/other_user}",
      "gists_url" : "https://api.github.com/users/stickies-v/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/stickies-v",
      "id" : 69010457,
      "login" : "stickies-v",
      "node_id" : "MDQ6VXNlcjY5MDEwNDU3",
      "organizations_url" : "https://api.github.com/users/stickies-v/orgs",
      "received_events_url" : "https://api.github.com/users/stickies-v/received_events",
      "repos_url" : "https://api.github.com/users/stickies-v/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/stickies-v/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/stickies-v/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/stickies-v"
   }
}
