{
   "assignee" : null,
   "assignees" : [],
   "author_association" : "CONTRIBUTOR",
   "body" : "This mitigates https://github.com/bitcoin/bitcoin/issues/15400\r\n\r\nI had a look into the issue today and this seems to be the best we can do given that the root causes some unexpected custom error code from the macOS kernel that python/asyncio doesn't know how to handle properly yet.",
   "closed_at" : "2019-07-24T11:21:51Z",
   "closed_by" : {
      "avatar_url" : "https://avatars0.githubusercontent.com/u/6399679?v=4",
      "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
      "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
      "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
      "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/MarcoFalke",
      "id" : 6399679,
      "login" : "MarcoFalke",
      "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
      "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
      "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
      "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/MarcoFalke"
   },
   "comments" : 5,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/16445/comments",
   "created_at" : "2019-07-23T20:00:02Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/16445/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/16445",
   "id" : 471905756,
   "labels" : [
      {
         "color" : "d4c5f9",
         "default" : false,
         "id" : 62963516,
         "name" : "Tests",
         "node_id" : "MDU6TGFiZWw2Mjk2MzUxNg==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/16445/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "MDExOlB1bGxSZXF1ZXN0MzAwNDQ5NDY3",
   "number" : 16445,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/16445.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/16445",
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/16445.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/16445"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "title" : "test: Skip flaky p2p_invalid_messages test on macOS",
   "updated_at" : "2019-07-24T14:40:00Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/16445",
   "user" : {
      "avatar_url" : "https://avatars2.githubusercontent.com/u/1322187?v=4",
      "events_url" : "https://api.github.com/users/fjahr/events{/privacy}",
      "followers_url" : "https://api.github.com/users/fjahr/followers",
      "following_url" : "https://api.github.com/users/fjahr/following{/other_user}",
      "gists_url" : "https://api.github.com/users/fjahr/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/fjahr",
      "id" : 1322187,
      "login" : "fjahr",
      "node_id" : "MDQ6VXNlcjEzMjIxODc=",
      "organizations_url" : "https://api.github.com/users/fjahr/orgs",
      "received_events_url" : "https://api.github.com/users/fjahr/received_events",
      "repos_url" : "https://api.github.com/users/fjahr/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/fjahr/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/fjahr/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/fjahr"
   }
}
