{
   "active_lock_reason" : "resolved",
   "assignee" : null,
   "assignees" : [],
   "author_association" : "CONTRIBUTOR",
   "body" : "When attempting to create a directory using \"/test_runner_â¿_ð_\", the following error is created.\r\n\r\n  `File \"test/functional/test_runner.py\", line 611, in <module>`\r\n  \t`    main()`\r\n`File \"test/functional/test_runner.py\", line 230, in main`\r\n  \t`    os.makedirs(tmpdir)`\r\n`File \"/usr/lib/python3.6/os.py\", line 220, in makedirs`\r\n\t`    mkdir(name, mode)` \r\n`UnicodeEncodeError: 'ascii' codec can't encode character '\\u20bf' in position 17: ordinal not in range(128)`\r\n\r\nSince, the code already checks for UTF-8 encoding/decoding at a previous place, it makes sense to check for this string too. \r\n\r\nI am using docker container for testing bitcoin and it comes with a default `sys.getfilesystemencoding() = ascii`, which is how I stumbled into this. \r\n\r\nIf this code will bloat the file, it might be better to use simple characters for directory name.",
   "closed_at" : "2018-09-24T20:21:30Z",
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
      "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
      "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
      "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
      "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/MarcoFalke",
      "id" : 6399679,
      "login" : "MarcoFalke",
      "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
      "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
      "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
      "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/MarcoFalke"
   },
   "comments" : 9,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/14237/comments",
   "created_at" : "2018-09-17T06:58:04Z",
   "draft" : false,
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/14237/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/14237",
   "id" : 360743371,
   "labels" : [
      {
         "color" : "d4c5f9",
         "default" : false,
         "description" : null,
         "id" : 62963516,
         "name" : "Tests",
         "node_id" : "MDU6TGFiZWw2Mjk2MzUxNg==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/14237/labels{/name}",
   "locked" : true,
   "milestone" : null,
   "node_id" : "MDExOlB1bGxSZXF1ZXN0MjE1ODg3NTI0",
   "number" : 14237,
   "performed_via_github_app" : null,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/14237.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/14237",
      "merged_at" : null,
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/14237.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/14237"
   },
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/14237/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "state_reason" : null,
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/14237/timeline",
   "title" : "Fix for test runner UnicodeDecodeError when utf-8 is not supported",
   "updated_at" : "2022-03-22T08:33:13Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/14237",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/6881849?v=4",
      "events_url" : "https://api.github.com/users/sanket1729/events{/privacy}",
      "followers_url" : "https://api.github.com/users/sanket1729/followers",
      "following_url" : "https://api.github.com/users/sanket1729/following{/other_user}",
      "gists_url" : "https://api.github.com/users/sanket1729/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/sanket1729",
      "id" : 6881849,
      "login" : "sanket1729",
      "node_id" : "MDQ6VXNlcjY4ODE4NDk=",
      "organizations_url" : "https://api.github.com/users/sanket1729/orgs",
      "received_events_url" : "https://api.github.com/users/sanket1729/received_events",
      "repos_url" : "https://api.github.com/users/sanket1729/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/sanket1729/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/sanket1729/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/sanket1729"
   }
}
