{
   "assignee" : null,
   "assignees" : [],
   "author_association" : "NONE",
   "body" : "**Is your feature request related to a problem? Please describe.**\r\n\r\nI'm always frustrated when almost half of a blockchain was downloaded and verified, and then happens a failure in a single block, which prevents the sync from proceeding forwardâ¦\r\n\r\n```\r\n2020-05-31T07:54:31Z Bitcoin Core version v0.19.0.1-gentoo (release build)\r\n...\r\n2020-05-31T07:54:40Z Loaded best chain: hashBestChain=000000000000000000be77bcc38cab3ec75b1918c4ce20904c9e48bacfd842c6 height=468087 date=2017-05-25T15:41:40Z progress=0.418393\r\n2020-05-31T07:54:40Z init message: Rewinding blocks...\r\n2020-05-31T07:54:41Z init message: Verifying blocks...\r\n2020-05-31T07:54:41Z Verifying last 6 blocks at level 3\r\n2020-05-31T07:54:41Z [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].\r\n2020-05-31T07:54:42Z No coin database inconsistencies in last 6 blocks (14028 transactions)\r\n...\r\n2020-05-31T07:54:42Z init message: Loading P2P addresses...\r\n2020-05-31T07:54:42Z *** Corrupt block found indicating potential hardware failure; shutting down\r\n2020-05-31T07:54:42Z Error: A fatal internal error occurred, see debug.log for details\r\n2020-05-31T07:54:42Z ERROR: ConnectTip: ConnectBlock 0000000000000000006338960b86655b587e2bdf12655041375707807ac84c7d failed, bad-txnmrklroot, hashMerkleRoot mismatch (code 16)\r\n2020-05-31T07:54:42Z Failed to connect best block (bad-txnmrklroot, hashMerkleRoot mismatch (code 16))\r\n```\r\n\r\n**Describe the solution you'd like**\r\n\r\nI'd like to have a setting in `bitcoind` that would allow for the offending block removal and re-downloading.\r\n\r\n**Describe alternatives you've considered**\r\n\r\nManually fixing something in local LevelDB files.\r\n\r\n**Additional context**\r\n\r\n- Seems to be a common issue among bitcoin newbies\r\n- https://github.com/bitcoin/bitcoin/issues/11576\r\n- Hardware could fail\r\n- I use cheap microSD card for storing the blockchain",
   "closed_at" : "2020-05-31T10:38:18Z",
   "closed_by" : {
      "avatar_url" : "https://avatars0.githubusercontent.com/u/6399679?v=4",
      "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
      "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
      "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
      "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/MarcoFalke",
      "id" : 6399679,
      "login" : "MarcoFalke",
      "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
      "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
      "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
      "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/MarcoFalke"
   },
   "comments" : 1,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/19121/comments",
   "created_at" : "2020-05-31T08:37:17Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/19121/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/19121",
   "id" : 627919185,
   "labels" : [
      {
         "color" : "7cf575",
         "default" : false,
         "description" : null,
         "id" : 64583,
         "name" : "Feature",
         "node_id" : "MDU6TGFiZWw2NDU4Mw==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Feature"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/19121/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "MDU6SXNzdWU2Mjc5MTkxODU=",
   "number" : 19121,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "title" : "Ability to recover a broken blockchain",
   "updated_at" : "2020-05-31T10:38:18Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/19121",
   "user" : {
      "avatar_url" : "https://avatars1.githubusercontent.com/u/6984946?v=4",
      "events_url" : "https://api.github.com/users/arbitrary-dev/events{/privacy}",
      "followers_url" : "https://api.github.com/users/arbitrary-dev/followers",
      "following_url" : "https://api.github.com/users/arbitrary-dev/following{/other_user}",
      "gists_url" : "https://api.github.com/users/arbitrary-dev/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/arbitrary-dev",
      "id" : 6984946,
      "login" : "arbitrary-dev",
      "node_id" : "MDQ6VXNlcjY5ODQ5NDY=",
      "organizations_url" : "https://api.github.com/users/arbitrary-dev/orgs",
      "received_events_url" : "https://api.github.com/users/arbitrary-dev/received_events",
      "repos_url" : "https://api.github.com/users/arbitrary-dev/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/arbitrary-dev/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/arbitrary-dev/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/arbitrary-dev"
   }
}
