[
   {
      "author_association" : "MEMBER",
      "body" : "One more: https://travis-ci.org/github/bitcoin/bitcoin/jobs/721444891#L3297",
      "created_at" : "2020-08-26T21:20:58Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/19139#issuecomment-681130554",
      "id" : 681130554,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/19139",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDY4MTEzMDU1NA==",
      "performed_via_github_app" : null,
      "updated_at" : "2020-08-26T21:20:58Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/681130554",
      "user" : {
         "avatar_url" : "https://avatars1.githubusercontent.com/u/32963518?v=4",
         "events_url" : "https://api.github.com/users/hebasto/events{/privacy}",
         "followers_url" : "https://api.github.com/users/hebasto/followers",
         "following_url" : "https://api.github.com/users/hebasto/following{/other_user}",
         "gists_url" : "https://api.github.com/users/hebasto/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/hebasto",
         "id" : 32963518,
         "login" : "hebasto",
         "node_id" : "MDQ6VXNlcjMyOTYzNTE4",
         "organizations_url" : "https://api.github.com/users/hebasto/orgs",
         "received_events_url" : "https://api.github.com/users/hebasto/received_events",
         "repos_url" : "https://api.github.com/users/hebasto/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/hebasto/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/hebasto/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/hebasto"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Do we have any more recent failures? Both logs linked have expired. If this hasn't been seen recently then I think this can be closed.",
      "created_at" : "2021-09-28T23:34:31Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/19139#issuecomment-929699203",
      "id" : 929699203,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/19139",
      "node_id" : "IC_kwDOABII5843ahWD",
      "performed_via_github_app" : null,
      "updated_at" : "2021-09-28T23:34:31Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/929699203",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/3211283?v=4",
         "events_url" : "https://api.github.com/users/meshcollider/events{/privacy}",
         "followers_url" : "https://api.github.com/users/meshcollider/followers",
         "following_url" : "https://api.github.com/users/meshcollider/following{/other_user}",
         "gists_url" : "https://api.github.com/users/meshcollider/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/meshcollider",
         "id" : 3211283,
         "login" : "meshcollider",
         "node_id" : "MDQ6VXNlcjMyMTEyODM=",
         "organizations_url" : "https://api.github.com/users/meshcollider/orgs",
         "received_events_url" : "https://api.github.com/users/meshcollider/received_events",
         "repos_url" : "https://api.github.com/users/meshcollider/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/meshcollider/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/meshcollider/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/meshcollider"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "It would be good to include an excerpt the next time this is seen",
      "created_at" : "2021-09-29T06:18:42Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/19139#issuecomment-929871137",
      "id" : 929871137,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/19139",
      "node_id" : "IC_kwDOABII5843bLUh",
      "performed_via_github_app" : null,
      "updated_at" : "2021-09-29T06:18:42Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/929871137",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "There is a failure in this test here: https://cirrus-ci.com/task/5241926094946304\r\n\r\nBut it isn't an AssertionError so it is likely a different issue.\r\n\r\nEDIT: This isn't specific to wallet_address_types.py, just coincidence. Also seen here in p2p_dns_seeds.py: https://cirrus-ci.com/task/4818027771330560 \r\n\r\n```\r\n test  2021-09-24T01:58:57.531000Z TestFramework (ERROR): Unexpected exception caught during testing \r\n                                   Traceback (most recent call last):\r\n                                     File \"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\cirrus-ci-build\\test\\functional\\test_framework\\test_framework.py\", line 131, in main\r\n                                       self.run_test()\r\n                                     File \"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\cirrus-ci-build\\test\\functional\\wallet_address_types.py\", line 299, in run_test\r\n                                       self.sync_mempools()\r\n                                     File \"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\cirrus-ci-build\\test\\functional\\test_framework\\test_framework.py\", line 673, in sync_mempools\r\n                                       r.syncwithvalidationinterfacequeue()\r\n                                     File \"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\cirrus-ci-build\\test\\functional\\test_framework\\coverage.py\", line 49, in __call__\r\n                                       return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\r\n                                     File \"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\cirrus-ci-build\\test\\functional\\test_framework\\authproxy.py\", line 144, in __call__\r\n                                       response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))\r\n                                     File \"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\cirrus-ci-build\\test\\functional\\test_framework\\authproxy.py\", line 107, in _request\r\n                                       self.__conn.request(method, path, postdata, headers)\r\n                                     File \"C:\\Python39\\lib\\http\\client.py\", line 1257, in request\r\n                                       self._send_request(method, url, body, headers, encode_chunked)\r\n                                     File \"C:\\Python39\\lib\\http\\client.py\", line 1303, in _send_request\r\n                                       self.endheaders(body, encode_chunked=encode_chunked)\r\n                                     File \"C:\\Python39\\lib\\http\\client.py\", line 1252, in endheaders\r\n                                       self._send_output(message_body, encode_chunked=encode_chunked)\r\n                                     File \"C:\\Python39\\lib\\http\\client.py\", line 1012, in _send_output\r\n                                       self.send(msg)\r\n                                     File \"C:\\Python39\\lib\\http\\client.py\", line 952, in send\r\n                                       self.connect()\r\n                                     File \"C:\\Python39\\lib\\http\\client.py\", line 923, in connect\r\n                                       self.sock = self._create_connection(\r\n                                     File \"C:\\Python39\\lib\\socket.py\", line 843, in create_connection\r\n                                       raise err\r\n                                     File \"C:\\Python39\\lib\\socket.py\", line 831, in create_connection\r\n                                       sock.connect(sa)\r\n                                   OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted\r\n```\r\n\r\nShould probably make a new issue for this.",
      "created_at" : "2021-09-29T10:23:24Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/19139#issuecomment-930047288",
      "id" : 930047288,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/19139",
      "node_id" : "IC_kwDOABII5843b2U4",
      "performed_via_github_app" : null,
      "updated_at" : "2021-09-29T10:27:28Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/930047288",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/3211283?v=4",
         "events_url" : "https://api.github.com/users/meshcollider/events{/privacy}",
         "followers_url" : "https://api.github.com/users/meshcollider/followers",
         "following_url" : "https://api.github.com/users/meshcollider/following{/other_user}",
         "gists_url" : "https://api.github.com/users/meshcollider/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/meshcollider",
         "id" : 3211283,
         "login" : "meshcollider",
         "node_id" : "MDQ6VXNlcjMyMTEyODM=",
         "organizations_url" : "https://api.github.com/users/meshcollider/orgs",
         "received_events_url" : "https://api.github.com/users/meshcollider/received_events",
         "repos_url" : "https://api.github.com/users/meshcollider/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/meshcollider/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/meshcollider/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/meshcollider"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Maybe https://github.com/bitcoin/bitcoin/pull/23089#discussion_r716001089",
      "created_at" : "2021-09-29T11:34:56Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/19139#issuecomment-930093451",
      "id" : 930093451,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/19139",
      "node_id" : "IC_kwDOABII5843cBmL",
      "performed_via_github_app" : null,
      "updated_at" : "2021-09-29T11:34:56Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/930093451",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?",
      "created_at" : "2022-08-14T13:58:21Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/19139#issuecomment-1214383584",
      "id" : 1214383584,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/19139",
      "node_id" : "IC_kwDOABII585IYgXg",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1214383584/reactions"
      },
      "updated_at" : "2022-08-14T13:58:21Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1214383584",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   }
]
