[
   {
      "author_association" : "MEMBER",
      "body" : "Thanks for the bug report.  Can you share a debug.log from a node affected by the issue?  If there might be sensitive information in it (wallet-related logs, IP addresses, etc) I am mostly interested in the debug messages around the relevant networking code, consisting of lines that include:\r\n`UpdateTip`, `Potential stale tip`, `disconnecting extra outbound peer`, `keeping outbound peer`, `setting try another outbound peer`, and `Making feeler connection`. ",
      "created_at" : "2019-02-26T13:51:25Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/15484#issuecomment-467445461",
      "id" : 467445461,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/15484",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDQ2NzQ0NTQ2MQ==",
      "updated_at" : "2019-02-26T13:51:25Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/467445461",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/7463573?v=4",
         "events_url" : "https://api.github.com/users/sdaftuar/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sdaftuar/followers",
         "following_url" : "https://api.github.com/users/sdaftuar/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sdaftuar/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sdaftuar",
         "id" : 7463573,
         "login" : "sdaftuar",
         "node_id" : "MDQ6VXNlcjc0NjM1NzM=",
         "organizations_url" : "https://api.github.com/users/sdaftuar/orgs",
         "received_events_url" : "https://api.github.com/users/sdaftuar/received_events",
         "repos_url" : "https://api.github.com/users/sdaftuar/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sdaftuar/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sdaftuar/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sdaftuar"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Thanks for the response. As I described in the issue, I only run the default client only with some additional logging messages. I didn't turn on the debug=net, unfortunately. \r\nI was looking for how IPs are inserted into new and tried table, actually, hence the logging messages are quite different.\r\nMy logging messages include almost all messages you requested actually, except \"setting try another outbound peer\". \r\nHere is the link to the shortened debug.log:\r\n[https://www.dropbox.com/s/769tyk1ftfpv3yh/shortened_debug.log?dl=0](url)\r\n\r\n",
      "created_at" : "2019-02-26T14:25:31Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/15484#issuecomment-467457823",
      "id" : 467457823,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/15484",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDQ2NzQ1NzgyMw==",
      "updated_at" : "2019-02-26T14:25:31Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/467457823",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/3724433?v=4",
         "events_url" : "https://api.github.com/users/muoitranduc/events{/privacy}",
         "followers_url" : "https://api.github.com/users/muoitranduc/followers",
         "following_url" : "https://api.github.com/users/muoitranduc/following{/other_user}",
         "gists_url" : "https://api.github.com/users/muoitranduc/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/muoitranduc",
         "id" : 3724433,
         "login" : "muoitranduc",
         "node_id" : "MDQ6VXNlcjM3MjQ0MzM=",
         "organizations_url" : "https://api.github.com/users/muoitranduc/orgs",
         "received_events_url" : "https://api.github.com/users/muoitranduc/received_events",
         "repos_url" : "https://api.github.com/users/muoitranduc/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/muoitranduc/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/muoitranduc/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/muoitranduc"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "I don't see any UpdateTip messages in there, could you please re-post with those included?",
      "created_at" : "2019-02-26T14:32:14Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/15484#issuecomment-467460452",
      "id" : 467460452,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/15484",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDQ2NzQ2MDQ1Mg==",
      "updated_at" : "2019-02-26T14:32:14Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/467460452",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/7463573?v=4",
         "events_url" : "https://api.github.com/users/sdaftuar/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sdaftuar/followers",
         "following_url" : "https://api.github.com/users/sdaftuar/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sdaftuar/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sdaftuar",
         "id" : 7463573,
         "login" : "sdaftuar",
         "node_id" : "MDQ6VXNlcjc0NjM1NzM=",
         "organizations_url" : "https://api.github.com/users/sdaftuar/orgs",
         "received_events_url" : "https://api.github.com/users/sdaftuar/received_events",
         "repos_url" : "https://api.github.com/users/sdaftuar/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sdaftuar/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sdaftuar/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sdaftuar"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "I checked the original debug.log. There is no \"UpdateTip\" message. \r\nDo you expect to see log message record by the following line? [https://github.com/bitcoin/bitcoin/blob/master/src/validation.cpp#L2263](url)\r\nIf so, there is no such message in the original debug.log as well. ",
      "created_at" : "2019-02-26T14:35:40Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/15484#issuecomment-467461708",
      "id" : 467461708,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/15484",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDQ2NzQ2MTcwOA==",
      "updated_at" : "2019-02-26T14:35:40Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/467461708",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/3724433?v=4",
         "events_url" : "https://api.github.com/users/muoitranduc/events{/privacy}",
         "followers_url" : "https://api.github.com/users/muoitranduc/followers",
         "following_url" : "https://api.github.com/users/muoitranduc/following{/other_user}",
         "gists_url" : "https://api.github.com/users/muoitranduc/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/muoitranduc",
         "id" : 3724433,
         "login" : "muoitranduc",
         "node_id" : "MDQ6VXNlcjM3MjQ0MzM=",
         "organizations_url" : "https://api.github.com/users/muoitranduc/orgs",
         "received_events_url" : "https://api.github.com/users/muoitranduc/received_events",
         "repos_url" : "https://api.github.com/users/muoitranduc/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/muoitranduc/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/muoitranduc/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/muoitranduc"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Could you please include the Bitcoin Core commit you built from and what local changes you made?",
      "created_at" : "2019-02-26T14:36:27Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/15484#issuecomment-467461988",
      "id" : 467461988,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/15484",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDQ2NzQ2MTk4OA==",
      "updated_at" : "2019-02-26T14:36:27Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/467461988",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "I think whatever bug is going on here is occurring on my own node as well; thanks again for this report, I'll take a look at my local logs and see what I can find.",
      "created_at" : "2019-02-26T14:53:07Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/15484#issuecomment-467468309",
      "id" : 467468309,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/15484",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDQ2NzQ2ODMwOQ==",
      "updated_at" : "2019-02-26T14:53:07Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/467468309",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/7463573?v=4",
         "events_url" : "https://api.github.com/users/sdaftuar/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sdaftuar/followers",
         "following_url" : "https://api.github.com/users/sdaftuar/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sdaftuar/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sdaftuar",
         "id" : 7463573,
         "login" : "sdaftuar",
         "node_id" : "MDQ6VXNlcjc0NjM1NzM=",
         "organizations_url" : "https://api.github.com/users/sdaftuar/orgs",
         "received_events_url" : "https://api.github.com/users/sdaftuar/received_events",
         "repos_url" : "https://api.github.com/users/sdaftuar/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sdaftuar/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sdaftuar/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sdaftuar"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "Great, thanks!\r\nFYI, I built from 0.17.0 release: https://github.com/bitcoin/bitcoin/archive/v0.17.0.zip\r\nI only added a few logging messages in addrman.cpp, net_processing.cpp and net.cpp. \r\n",
      "created_at" : "2019-02-26T14:59:10Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/15484#issuecomment-467470830",
      "id" : 467470830,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/15484",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDQ2NzQ3MDgzMA==",
      "updated_at" : "2019-03-01T05:20:51Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/467470830",
      "user" : {
         "avatar_url" : "https://avatars2.githubusercontent.com/u/3724433?v=4",
         "events_url" : "https://api.github.com/users/muoitranduc/events{/privacy}",
         "followers_url" : "https://api.github.com/users/muoitranduc/followers",
         "following_url" : "https://api.github.com/users/muoitranduc/following{/other_user}",
         "gists_url" : "https://api.github.com/users/muoitranduc/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/muoitranduc",
         "id" : 3724433,
         "login" : "muoitranduc",
         "node_id" : "MDQ6VXNlcjM3MjQ0MzM=",
         "organizations_url" : "https://api.github.com/users/muoitranduc/orgs",
         "received_events_url" : "https://api.github.com/users/muoitranduc/received_events",
         "repos_url" : "https://api.github.com/users/muoitranduc/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/muoitranduc/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/muoitranduc/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/muoitranduc"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "ping @EthanHeilman \r\n\r\nI think this is a buggy interaction between addrman and net relating to collisions and feelers.  If we encounter a collision in the tried table with something in a network group that we already have an outbound connection to, then we can get stuck with an entry in `m_tried_collisions` that will never be resolved.\r\n\r\nIn the debug.log you posted, I noticed that the feelers stopped regularly happening when the addrman encountered a collision in the tried table:\r\n\r\n```\r\n2019-01-30T18:43:09Z ResolveCollisions_, 78.108.187.246:8333, Collision with 35.178.76.8:8333 in tried table at Bucket = 181 and Slot = 28\r\n```\r\n\r\nAt the time that this collision with 35.178.76.8 occurred, your node was already connected outbound to another node with the same network group:\r\n```\r\n2019-01-27T02:17:23Z ProcessMessage, VERACK, New outgoing connection: peeraddr=35.178.95.164:8333 , number of incoming: 68 , number of outgoing: 8 \r\n```\r\n\r\nHere's the relevant code snippet from `CConnMan::ThreadOpenConnections()` that shows what happens:\r\n\r\nhttps://github.com/bitcoin/bitcoin/blob/master/src/net.cpp#L1755-L1801\r\n\r\nIn particular, in our loop where we try to send a feeler connection to something that had a collision, we break if the address is to something in a network group we're already connected to.  However the collision cannot be resolved until we try to connect to the ip address and fail; here is the relevant code from the addrman's `ResolveCollisions()`:\r\n\r\nhttps://github.com/bitcoin/bitcoin/blob/master/src/addrman.cpp#L551-L571\r\n\r\nSo we get stuck, with no way to try more feelers, and no way to connect to the one the feeler code would like to test.\r\n\r\nI'm not sure what the best fix is; I think we could either connect a feeler anyway to things in the same network group, or we could make it so that nothing stays in the m_tried_collisions set for too long before being resolved somehow, or both...\r\n\r\n@muoitranduc Your debug.log that shows both colliding entries was very helpful for tracking this down!",
      "created_at" : "2019-02-26T16:45:20Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/15484#issuecomment-467516182",
      "id" : 467516182,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/15484",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDQ2NzUxNjE4Mg==",
      "updated_at" : "2019-02-26T16:49:01Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/467516182",
      "user" : {
         "avatar_url" : "https://avatars0.githubusercontent.com/u/7463573?v=4",
         "events_url" : "https://api.github.com/users/sdaftuar/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sdaftuar/followers",
         "following_url" : "https://api.github.com/users/sdaftuar/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sdaftuar/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sdaftuar",
         "id" : 7463573,
         "login" : "sdaftuar",
         "node_id" : "MDQ6VXNlcjc0NjM1NzM=",
         "organizations_url" : "https://api.github.com/users/sdaftuar/orgs",
         "received_events_url" : "https://api.github.com/users/sdaftuar/received_events",
         "repos_url" : "https://api.github.com/users/sdaftuar/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sdaftuar/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sdaftuar/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sdaftuar"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : ">I think we could either connect a feeler anyway to things in the same network group, or we could make it so that nothing stays in the m_tried_collisions set for too long before being resolved somehow, or both...\r\n\r\nI agree with doing both fixes: \r\n\r\n1. Having it ignore groups is the right behavior.\r\n2. However we need a way to clear out an addr that is repeatedly being test and not being resolved.",
      "created_at" : "2019-02-26T21:11:21Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/15484#issuecomment-467615209",
      "id" : 467615209,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/15484",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDQ2NzYxNTIwOQ==",
      "updated_at" : "2019-02-26T21:15:51Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/467615209",
      "user" : {
         "avatar_url" : "https://avatars3.githubusercontent.com/u/274814?v=4",
         "events_url" : "https://api.github.com/users/EthanHeilman/events{/privacy}",
         "followers_url" : "https://api.github.com/users/EthanHeilman/followers",
         "following_url" : "https://api.github.com/users/EthanHeilman/following{/other_user}",
         "gists_url" : "https://api.github.com/users/EthanHeilman/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/EthanHeilman",
         "id" : 274814,
         "login" : "EthanHeilman",
         "node_id" : "MDQ6VXNlcjI3NDgxNA==",
         "organizations_url" : "https://api.github.com/users/EthanHeilman/orgs",
         "received_events_url" : "https://api.github.com/users/EthanHeilman/received_events",
         "repos_url" : "https://api.github.com/users/EthanHeilman/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/EthanHeilman/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/EthanHeilman/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/EthanHeilman"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Following up on whether #15486 resolved this issue or if additional logic to ResolveCollisions() is needed as per [@sdaftuar's comment](https://github.com/bitcoin/bitcoin/pull/15486#issuecomment-467601659). cc @muoitranduc ",
      "created_at" : "2020-05-06T12:13:05Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/15484#issuecomment-624612920",
      "id" : 624612920,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/15484",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDYyNDYxMjkyMA==",
      "updated_at" : "2020-05-06T12:13:05Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/624612920",
      "user" : {
         "avatar_url" : "https://avatars1.githubusercontent.com/u/755825?v=4",
         "events_url" : "https://api.github.com/users/adamjonas/events{/privacy}",
         "followers_url" : "https://api.github.com/users/adamjonas/followers",
         "following_url" : "https://api.github.com/users/adamjonas/following{/other_user}",
         "gists_url" : "https://api.github.com/users/adamjonas/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/adamjonas",
         "id" : 755825,
         "login" : "adamjonas",
         "node_id" : "MDQ6VXNlcjc1NTgyNQ==",
         "organizations_url" : "https://api.github.com/users/adamjonas/orgs",
         "received_events_url" : "https://api.github.com/users/adamjonas/received_events",
         "repos_url" : "https://api.github.com/users/adamjonas/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/adamjonas/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/adamjonas/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/adamjonas"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "From email with @muoitranduc:\r\n\r\n\"...we couldn't reproduce the corner cases that we faced with our newly-spawned nodes. I understand that the logic has been modified even further with the anchor connections. Hence, I guess it is safe to close the issue because its only purpose is to guarantee feeler connections can be established.\"\r\n\r\nThis looks like it can be closed.",
      "created_at" : "2020-10-20T14:27:44Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/15484#issuecomment-712894003",
      "id" : 712894003,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/15484",
      "node_id" : "MDEyOklzc3VlQ29tbWVudDcxMjg5NDAwMw==",
      "performed_via_github_app" : null,
      "updated_at" : "2020-10-20T14:27:44Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/712894003",
      "user" : {
         "avatar_url" : "https://avatars1.githubusercontent.com/u/755825?v=4",
         "events_url" : "https://api.github.com/users/adamjonas/events{/privacy}",
         "followers_url" : "https://api.github.com/users/adamjonas/followers",
         "following_url" : "https://api.github.com/users/adamjonas/following{/other_user}",
         "gists_url" : "https://api.github.com/users/adamjonas/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/adamjonas",
         "id" : 755825,
         "login" : "adamjonas",
         "node_id" : "MDQ6VXNlcjc1NTgyNQ==",
         "organizations_url" : "https://api.github.com/users/adamjonas/orgs",
         "received_events_url" : "https://api.github.com/users/adamjonas/received_events",
         "repos_url" : "https://api.github.com/users/adamjonas/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/adamjonas/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/adamjonas/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/adamjonas"
      }
   }
]
