{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "MEMBER",
   "body" : "https://cirrus-ci.com/task/4685360343023616?command=ci#L1078\r\n```\r\n50/194 - interface_zmq.py failed, Duration: 97 s\r\nstdout:\r\n2020-12-07T13:33:26.675000Z TestFramework (INFO): Initializing test directory /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_â¿_ð_20201207_132422/interface_zmq_150\r\n2020-12-07T13:33:50.656000Z TestFramework (INFO): Generate 5 blocks (and 5 coinbase txes)\r\n2020-12-07T13:33:51.912000Z TestFramework (INFO): Wait for tx from second node\r\n2020-12-07T13:33:55.422000Z TestFramework (INFO): Test the getzmqnotifications RPC\r\n2020-12-07T13:33:55.428000Z TestFramework (INFO): Testing 'sequence' publisher\r\n2020-12-07T13:34:02.510000Z TestFramework (INFO): Wait for tx from second node\r\n2020-12-07T13:34:04.838000Z TestFramework (INFO): Testing sequence notifications with mempool sequence values\r\n2020-12-07T13:34:04.838000Z TestFramework (INFO): Testing RBF notification\r\n2020-12-07T13:34:19.694000Z TestFramework (INFO): Testing reorg notifications\r\n2020-12-07T13:34:21.807000Z TestFramework (INFO): Evict mempool transaction by block conflict\r\n2020-12-07T13:34:27.378000Z TestFramework (INFO): Testing 'mempool sync' usage of sequence notifier\r\n2020-12-07T13:35:02.427000Z TestFramework (ERROR): Unexpected exception caught during testing\r\nTraceback (most recent call last):\r\n  File \"/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py\", line 126, in main\r\n    self.run_test()\r\n  File \"/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/interface_zmq.py\", line 76, in run_test\r\n    self.test_reorg()\r\n  File \"/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/interface_zmq.py\", line 201, in test_reorg\r\n    assert_equal(self.nodes[0].getbestblockhash(), hashblock.receive().hex())\r\n  File \"/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/interface_zmq.py\", line 37, in receive\r\n    topic, body, seq = self.socket.recv_multipart()\r\n  File \"/usr/lib/python3/dist-packages/zmq/sugar/socket.py\", line 475, in recv_multipart\r\n    parts = [self.recv(flags, copy=copy, track=track)]\r\n  File \"zmq/backend/cython/socket.pyx\", line 791, in zmq.backend.cython.socket.Socket.recv\r\n  File \"zmq/backend/cython/socket.pyx\", line 827, in zmq.backend.cython.socket.Socket.recv\r\n  File \"zmq/backend/cython/socket.pyx\", line 191, in zmq.backend.cython.socket._recv_copy\r\n  File \"zmq/backend/cython/socket.pyx\", line 186, in zmq.backend.cython.socket._recv_copy\r\n  File \"zmq/backend/cython/checkrc.pxd\", line 19, in zmq.backend.cython.checkrc._check_rc\r\nzmq.error.Again: Resource temporarily unavailable\r\n2020-12-07T13:35:02.479000Z TestFramework (INFO): Stopping nodes\r\n2020-12-07T13:35:03.401000Z TestFramework (WARNING): Not cleaning up dir /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_â¿_ð_20201207_132422/interface_zmq_150\r\n2020-12-07T13:35:03.402000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_â¿_ð_20201207_132422/interface_zmq_150/test_framework.log\r\n2020-12-07T13:35:03.402000Z TestFramework (ERROR): \r\n2020-12-07T13:35:03.402000Z TestFramework (ERROR): Hint: Call /tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/combine_logs.py '/tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_â¿_ð_20201207_132422/interface_zmq_150' to consolidate all logs\r\n2020-12-07T13:35:03.402000Z TestFramework (ERROR): \r\n2020-12-07T13:35:03.403000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.\r\n2020-12-07T13:35:03.403000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues\r\n2020-12-07T13:35:03.403000Z TestFramework (ERROR): \r\n```",
   "closed_at" : "2021-01-15T00:59:39Z",
   "closed_by" : {
      "avatar_url" : "https://avatars2.githubusercontent.com/u/863730?v=4",
      "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
      "followers_url" : "https://api.github.com/users/fanquake/followers",
      "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
      "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/fanquake",
      "id" : 863730,
      "login" : "fanquake",
      "node_id" : "MDQ6VXNlcjg2MzczMA==",
      "organizations_url" : "https://api.github.com/users/fanquake/orgs",
      "received_events_url" : "https://api.github.com/users/fanquake/received_events",
      "repos_url" : "https://api.github.com/users/fanquake/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/fanquake"
   },
   "comments" : 2,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/20590/comments",
   "created_at" : "2020-12-07T13:51:43Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/20590/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/20590",
   "id" : 758524826,
   "labels" : [
      {
         "color" : "FBBAAB",
         "default" : false,
         "description" : null,
         "id" : 64585,
         "name" : "Bug",
         "node_id" : "MDU6TGFiZWw2NDU4NQ==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Bug"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/20590/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "MDU6SXNzdWU3NTg1MjQ4MjY=",
   "number" : 20590,
   "performed_via_github_app" : null,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "title" : "qa: Intermittent failure in interface_zmq.py \"Resource temporarily unavailable\"",
   "updated_at" : "2021-01-15T00:59:39Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/20590",
   "user" : {
      "avatar_url" : "https://avatars1.githubusercontent.com/u/32963518?v=4",
      "events_url" : "https://api.github.com/users/hebasto/events{/privacy}",
      "followers_url" : "https://api.github.com/users/hebasto/followers",
      "following_url" : "https://api.github.com/users/hebasto/following{/other_user}",
      "gists_url" : "https://api.github.com/users/hebasto/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/hebasto",
      "id" : 32963518,
      "login" : "hebasto",
      "node_id" : "MDQ6VXNlcjMyOTYzNTE4",
      "organizations_url" : "https://api.github.com/users/hebasto/orgs",
      "received_events_url" : "https://api.github.com/users/hebasto/received_events",
      "repos_url" : "https://api.github.com/users/hebasto/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/hebasto/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/hebasto/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/hebasto"
   }
}
