{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "NONE",
   "body" : "copy my posts from Bitcointalk forum since January, hope this is ok...\r\n\r\nFirst\r\n-Issue started beginning this year with v0.21.0 when open Bitcoin Core, after receiving payment from nicehash.\r\nAlways while loading the same block, I think the one in which the Nicehash transfer is located, Bitcoin Core was closed without an error message. After trying several times to reinitialize, even from an older backup of my wallet.dat, \r\n\r\n-Try to import my wallet.dat after finished synching with a new wallet, but during inilizing my old wallet the same issue comes back, Bitcoin Core just shutdown without an error message and at same pos in debug.log\r\n\r\n-Reinstalling v0.20.1 and the problem was resolved. \r\n\r\n-Reinstall 0.21.0 again, clean dbug.log and start with -reindex and -rescan.\r\nAfter synching for a couple of hours Bitcon Core was shutdown.\r\nRestart 2 times with same resault, the programm crashes without any error messege while synching the transaction from nicehash\r\nThis was few months ago, after that I returned to v 0.20.1 and it works like a charm without problems an weekly ingoing tx from nicehash.\r\n\r\n\r\nThen\r\nStill the same problem with version 0.21.1 whenever a new transaction comes in from Nicehash.\r\nCould it be possible the latest BitcoinCore versions has a bug? Or someone might have the same problem or can tell what exactly is the difference from latest to previous versions so this problem could occur.\r\nCan't imagine that it is due to my hardware or SW, since the problem is only with the incoming transactions from Nicehash and that only since Januar this year and since v0.21.0. This is for sure because if I re-syncronize the entire chain with latest BitcoinCore Version, it runs through all the years (many transaction over the past 4 years also incom from NH) until Januar 2021 without any problems and then always crashes on the same transaction from Nicehash dad0f505c7c9697e1b7b79ecc7133701fd0a4424993ec27770191bfb6a290763 (as in my first post). reverting to v0.20.1, sync this transaction (no problem), after that revert again to v0.21 and run until next tx from Nicehash with same problem..\r\nCould it have to do with the size of transactions, because those from Nicehash are much larger than other, 7kb compared to usually a few hundred bytes.\r\n\r\n\r\nNow\r\njust to confirm after I ran BitcoinCore 0.21.1 without any problems for the entire last week until the next transaction from Nicehash arrived yesterday.\r\nAfter the crash and several attempts with the same error at the same position (program closes when synchronizing the Nicehash transaction without a message) I pushed v0.20.1 into the program directory, started it and synchronized everything without problems.\r\nThen switched back to the current v0.21.1 and its up and running again.\r\n\r\nIf you are interested, you can have a look at the last two days below debug log, don't think I need to comment\r\n\r\nTx from NH 2021-05-21 01:12\r\naf4b27fd3e6917ddf39a16e159d2c20a4703ebaeffc554d3e29a780855a29525\r\n\r\nDebug log with first attempt to load the NH tx\r\n[debug.log](https://github.com/bitcoin/bitcoin/files/6527448/debug.log)\r\n 2021-05-21T02:34:15Z",
   "closed_at" : "2021-09-26T03:41:41Z",
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/22902796?v=4",
      "events_url" : "https://api.github.com/users/wasisdn/events{/privacy}",
      "followers_url" : "https://api.github.com/users/wasisdn/followers",
      "following_url" : "https://api.github.com/users/wasisdn/following{/other_user}",
      "gists_url" : "https://api.github.com/users/wasisdn/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/wasisdn",
      "id" : 22902796,
      "login" : "wasisdn",
      "node_id" : "MDQ6VXNlcjIyOTAyNzk2",
      "organizations_url" : "https://api.github.com/users/wasisdn/orgs",
      "received_events_url" : "https://api.github.com/users/wasisdn/received_events",
      "repos_url" : "https://api.github.com/users/wasisdn/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/wasisdn/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/wasisdn/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/wasisdn"
   },
   "comments" : 6,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/22024/comments",
   "created_at" : "2021-05-23T02:47:50Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/22024/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/22024",
   "id" : 898922413,
   "labels" : [
      {
         "color" : "08a781",
         "default" : false,
         "description" : null,
         "id" : 149424,
         "name" : "Wallet",
         "node_id" : "MDU6TGFiZWwxNDk0MjQ=",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Wallet"
      },
      {
         "color" : "884400",
         "default" : false,
         "description" : null,
         "id" : 234877,
         "name" : "Windows",
         "node_id" : "MDU6TGFiZWwyMzQ4Nzc=",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Windows"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/22024/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "MDU6SXNzdWU4OTg5MjI0MTM=",
   "number" : 22024,
   "performed_via_github_app" : null,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/22024/timeline",
   "title" : "wallet: Bitcoin Core v0.21.1 issue with incoming transaction",
   "updated_at" : "2021-09-26T03:41:41Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/22024",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/22902796?v=4",
      "events_url" : "https://api.github.com/users/wasisdn/events{/privacy}",
      "followers_url" : "https://api.github.com/users/wasisdn/followers",
      "following_url" : "https://api.github.com/users/wasisdn/following{/other_user}",
      "gists_url" : "https://api.github.com/users/wasisdn/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/wasisdn",
      "id" : 22902796,
      "login" : "wasisdn",
      "node_id" : "MDQ6VXNlcjIyOTAyNzk2",
      "organizations_url" : "https://api.github.com/users/wasisdn/orgs",
      "received_events_url" : "https://api.github.com/users/wasisdn/received_events",
      "repos_url" : "https://api.github.com/users/wasisdn/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/wasisdn/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/wasisdn/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/wasisdn"
   }
}
