{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "NONE",
   "body" : "Hello everyone: \r\nI am running: \r\n{\r\n  \"version\": 180000,\r\n  \"protocolversion\": 70015,\r\n  \"walletversion\": 169900,\r\n\r\n\r\nIn the debug log I get: \r\n2019-07-05T05:47:37Z UpdateTip: new best=00000000000000000006a8e968937ed0d26cba95af48aec9a35030dae34068ea height=583923 version=0x20000000 log2_work=90.811056 tx=431748422 date='2019-07-05T05:47:31Z' progress=1.000000 cache=67.4MiB(597483txo) warning='43 of last 100 blocks have unexpected version\r\n\r\nAs I am running version 0.18, I would have expected this kind of message go away, as the message \"unknown version\"was deactivated in the latest release. \r\nWhat is the difference between \"unexpected version\" and \"unknown version\"? \r\nWhy one warning has been suppressed with latest release and the other is still present (and quite common as I can see?)\r\nThis different approach on very similar errors is generating user confusion.\r\nThank you. \r\n",
   "closed_at" : "2020-04-27T01:06:21Z",
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
      "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
      "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
      "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
      "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/MarcoFalke",
      "id" : 6399679,
      "login" : "MarcoFalke",
      "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
      "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
      "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
      "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/MarcoFalke"
   },
   "comments" : 20,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/16343/comments",
   "created_at" : "2019-07-05T06:02:06Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/16343/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/16343",
   "id" : 464475255,
   "labels" : [],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/16343/labels{/name}",
   "locked" : true,
   "milestone" : null,
   "node_id" : "MDU6SXNzdWU0NjQ0NzUyNTU=",
   "number" : 16343,
   "performed_via_github_app" : null,
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/16343/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "state_reason" : "completed",
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/16343/timeline",
   "title" : " warning='45 of last 100 blocks have unexpected version'",
   "updated_at" : "2023-05-16T10:01:57Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/16343",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/44410539?v=4",
      "events_url" : "https://api.github.com/users/Fillippone/events{/privacy}",
      "followers_url" : "https://api.github.com/users/Fillippone/followers",
      "following_url" : "https://api.github.com/users/Fillippone/following{/other_user}",
      "gists_url" : "https://api.github.com/users/Fillippone/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/Fillippone",
      "id" : 44410539,
      "login" : "Fillippone",
      "node_id" : "MDQ6VXNlcjQ0NDEwNTM5",
      "organizations_url" : "https://api.github.com/users/Fillippone/orgs",
      "received_events_url" : "https://api.github.com/users/Fillippone/received_events",
      "repos_url" : "https://api.github.com/users/Fillippone/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/Fillippone/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/Fillippone/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/Fillippone"
   }
}
