{
   "assignee" : null,
   "assignees" : [],
   "author_association" : "NONE",
   "body" : "macOS 10.13.1\r\nbitcoinCore 0.15.1 downloaded from bitcoin.org\r\nSynology DSM 6.1.4-15217 Update 2\r\n\r\nWhen I first start bitcoinCore , I select a folder on my Synology NAS.\r\n\r\nWhen I validate, an error message pops up:\r\n\"Cannot brain a lock on data directory / Volumes/home. Bitcoin Core is probably already running. Operation not supported\"\r\n\r\nAfter I acknowledge by clicking on the OK button, the application closes. \r\n\r\nIf I start the application again, the same error message appears without prompting me for a new folder. \r\n \r\nThis is reproducible 100% of the time. \r\n\r\nThe only error message I found was in /var/log/syslog:\r\niMac com.apple.xpc.launchd[1] (org.bitcoinfoundation.Bitcoin-Qt.22648[7797]): Service exited with abnormal code: 1\r\n",
   "closed_at" : "2017-12-07T22:29:38Z",
   "closed_by" : {
      "avatar_url" : "https://avatars1.githubusercontent.com/u/33880848?v=4",
      "events_url" : "https://api.github.com/users/fgc92/events{/privacy}",
      "followers_url" : "https://api.github.com/users/fgc92/followers",
      "following_url" : "https://api.github.com/users/fgc92/following{/other_user}",
      "gists_url" : "https://api.github.com/users/fgc92/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/fgc92",
      "id" : 33880848,
      "login" : "fgc92",
      "node_id" : "MDQ6VXNlcjMzODgwODQ4",
      "organizations_url" : "https://api.github.com/users/fgc92/orgs",
      "received_events_url" : "https://api.github.com/users/fgc92/received_events",
      "repos_url" : "https://api.github.com/users/fgc92/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/fgc92/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/fgc92/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/fgc92"
   },
   "comments" : 3,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11801/comments",
   "created_at" : "2017-11-30T16:16:58Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11801/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/11801",
   "id" : 278179995,
   "labels" : [],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11801/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "MDU6SXNzdWUyNzgxNzk5OTU=",
   "number" : 11801,
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "title" : "Cannot obtain a lock on data directory",
   "updated_at" : "2017-12-07T22:29:38Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/11801",
   "user" : {
      "avatar_url" : "https://avatars1.githubusercontent.com/u/33880848?v=4",
      "events_url" : "https://api.github.com/users/fgc92/events{/privacy}",
      "followers_url" : "https://api.github.com/users/fgc92/followers",
      "following_url" : "https://api.github.com/users/fgc92/following{/other_user}",
      "gists_url" : "https://api.github.com/users/fgc92/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/fgc92",
      "id" : 33880848,
      "login" : "fgc92",
      "node_id" : "MDQ6VXNlcjMzODgwODQ4",
      "organizations_url" : "https://api.github.com/users/fgc92/orgs",
      "received_events_url" : "https://api.github.com/users/fgc92/received_events",
      "repos_url" : "https://api.github.com/users/fgc92/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/fgc92/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/fgc92/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/fgc92"
   }
}
